AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Prueba desarrollador massivian

Resources:
  PruebaMasivianArbolesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.masivian.prueba.arboles.red.aws.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ./build/distributions/arboles-1.0-SNAPSHOT.zip
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PruebaMasivianArboles:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/trees'
    Export:
      Name: PruebaMasivianArboles